package problemaNro2;

public enum Posicion {
	
	ARQUERO, DEFENSOR_CENTRAL, DEFENSOR_IZQUIERDO, DEFENSOR_DERECHO,
	MEDIOCAMPISTA_DE_CONTENCION, MEDIOCAMPISTA_OFENSIVO, MEDIOCAMPISTA_CENTRAL,
	MEDIOCAMPISTA_IZQUIERDO, MEDIOCAMPISTA_DERECHO, DELANTERO_CENTRO,
	SEGUNDO_DELANTERO, EXTREMO_IZQUIERDO, EXTREMO_DERECHO;

}
